theme: jekyll-theme-slate
name: James R. Castle, Ph.D.

markdown: kramdown

github_username:        jrcastle
linkedin_username:      jrcastle90
stackoverflow_username: jrcastle90
email:                  jrcastle90@gmail.com