title: James R. Castle
description: Physicist, data scientist, software developer, gamer
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

name: James R. Castle

github_username:        jrcastle
linkedin_username:      jrcastle90
stackoverflow_username: jrcastle90
email:                  jrcastle90@gmail.com